### ISSUE TITLE
Form with single date question fails with TypeError

### ISSUE THREAD

**Issue by yanokwa** [enketo/enketo-express#537]
1. Go to http://xlsform.getodk.org (running Enketo v6.0.0-8-g4f65fcf)
2. Upload a form with single date question (or use [bug.xlsx](https://github.com/enketo/enketo-express/files/11030121/bug.xlsx))
3. Form converts, but returns `TypeError: this.$fakeDateI.datepicker is not a function` on preview.

Works on 6.0.0.

**Comment by lognaturel** [comment]
Something has changed in how/when jQuery extensions are loaded

**Comment by yanokwa** [comment]
https://forum.getodk.org/t/xlsform-online-v2-x-error-main-swipe/40845 reports a `TypeError: $main.swipe is not a function`

Probably related.

**Comment by eyelidlessness** [comment]
I found the `$main.swipe` case just a bit ago. They are definitely related. Both seem to be caused by the recent jQuery version bump. For now I think we can safely just roll that back. But it's surprising either extension is affected by the changes in the particular jQuery release, as neither seem to be directly using anything affected by the change.
